### ISSUE TITLE
Minimizes on wake, sometimes

### ISSUE THREAD

**Issue by networks1** [pot8oe/mythmote#91]
I'm having a problem with the app on a Note 4 running M.  If the phone times out and goes to sleep, when I wake the phone the app minimizes and I have to go into the active  apps list  to restore it. It's a little annoying as what should be one operation turns into 3. The odd thing is that this happens randomly. Sometimes it does and sometimes it doesn't, and I've even tried it with the phone sitting on a table to ensure its not due to an accidental touch.

**Comment by pot8oe** [comment]
Mythmote will not minimize itself under any circumstances. Do you know if
mythmote is crashing or is another app (ie: home screen) becoming the
active app?

**Comment by dmfrey** [comment]
what launcher do you have installed as well?

**Comment by networks1** [comment]
I'm using novalauncher. AFAIK no other app becomes active.  Mythmote appears very briefly (flashes, really) then it goes to the lock screen.  When I unlock I'm at the home screen. Like I said the weird thing is that it only happens sometimes, and I've not been able to trace it to particular conditions.

**Comment by pot8oe** [comment]
Mythmote should stay visible above the lock screen and not require
unlocking of the device. This only works if the phone locks with mythmote
active. I wonder if the lock screen is forcing itself ontop of mythmote.
This might be a Samsung lock screen glitch unless you are getting a crash
report for mythmote. Do you have multiple methods of waking the screen? Do
you have lock screen widgets setup?


On May 19, 2017 20:16, "networks1" <notifications@github.com> wrote:

I'm using novalauncher. AFAIK no other app becomes active. Mythmote appears
very briefly (flashes, really) then it goes to the lock screen. When I
unlock I'm at the home screen. Like I said the weird thing is that it only
happens sometimes, and I've not been able to trace it to particular
conditions.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pot8oe/mythmote/issues/91#issuecomment-302837195>, or mute
the thread

**Comment by dmfrey** [comment]
Can you try it with the sick launcher on your phone?

**Comment by pot8oe** [comment]
I think the sick launcher fixed it ;-P
